### ISSUE TITLE
Windows/Linux path naming intercompatibility mode for %artist%, %tags% and %title%

### ISSUE THREAD

**Issue by mugi-jiichan** [Nandaka/PixivUtil2#1033]
### Prerequisites

* [x] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or -[commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ? **release**
* [x] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

Hi,
thank you for the continuous updates and keeping this wonderful tool running.

I've set up the recent release on a Linux machine because of #972 , and it really works very nicely so far. However, I've noticed that the python script has created folder names that have asterisks, colons and question marks (haven't seen any pipe characters yet).

There are workarounds in Linux to be able to access those paths, so I wouldn't have a problem moving the downloads onto my NAS archive.

However, those folders wouldn't work with Windows due to the forbidden characters. I've tested access via Samba shares, and they're either mangled into a 8.3 scheme or just inaccessible because of the forbidden characters if mangling is being turned off in the Samba server.

I hope I haven't missed something here that is already featured in the code, but is there a way to implement a character replacement mode to Windows-safe characters to create intercompatible paths?

If not, I guess I could go though the downloads with 'find' command and replace all characters that are illegal for Windows with an underscore just like in the Windows version. Thinking of `find . (mindepth/maxdepth) -type d -name "*\*?*"` to look for the folders that contain asterisks and then just rename them... (still learning bash)

Thank you for your time.

### Steps to Reproduce

1. Use any download mode - mode 2 by image ID serves the best as test.
2. Example image ID 93074500 or 93231326 (from the log files, both contain asterisks)
3. 

**Expected behavior:** On Windows, the question mark in the character title is replaced with an underscore.

**Actual behavior:** On Linux, the question mark in the character title is being kept.

**Log files:** 
[pixivutil.log](https://github.com/Nandaka/PixivUtil2/files/7409399/pixivutil.log) - Linux
[pixivutil.log](https://github.com/Nandaka/PixivUtil2/files/7409392/pixivutil.log) - Windows

### Versions

PixivDownloader2 version 20211022 (Linux/Python vs. Windows)

**Comment by cglmrfreeman** [comment]
I have run into this issue several times #861 #889 and have asked to implement a filtering system based on the operating system as a setting rather than letting PixivUtil2 detect this every time. As @Nandaka mentioned above, PixivUtil2 has it's own detection if the system is running Windows and filters it. But if you are on Linux and with to use these filters, you _must_ use the custom filter characters like so in the config.ini: `customBadChars = "$'*:<>?\|`

I find this to be very redundant when an `osSaveType = Windows` would have sufficed as an override to the `if platform.system() == 'Windows':` detection, where the config.ini would set osSaveType to `platform.system()` on creation.

Also, because I feel it's necessary to bring this up, if you are saving images to an NTFS formatted drive from Linux, you _have_ to use these filters, else PixivUtil2 will run into `"Invalid Argument" OSError` trying to save Linux allowable filenames to a filesystem that does not support them.
