### ISSUE TITLE
RFC: Add option to save converted extension of ugoira instead of zip

### ISSUE THREAD

**Issue by NHOrus** [Nandaka/PixivUtil2#1140]
Ok, still my weird workflow and my desires to smooth it in various ways.

Currently, if there's an Ugoira file downloaded and then converted, PixivUtil2 saves original file extension, zip.
There's no zip file if `deleteZipFile = True`. Maybe add some kind of `countCreatedAsDownloaded` option in Ugoira section of config that , if true, writes to Downloaded_on list name of Ugoira/apng/gif/webwhatever that was created after processing Ugoira.

Hence, four questions:

1.  Is this name the best?
2. Should it prevent creation of zip file line in downloaded files if `deleteZipFile = True` ?
3. If not, should there be separate option for that?
3a. How this separate option should be called?
4. If `deleteZipFile = True`, should we ever note anything about ugoira archives if `countCreatedAsDownloaded = False` ?

And, of course, this is all modulo Fanbox zip archive rewards, which should be left as is.

I will write the implementation myself, soon, but I really want people's opinion on how best to shape this feature.

**Comment by Nandaka** [comment]
if you asking about the file extension, this is because what HoneyView use (and I'm using it as image viewer).
https://extension.nirsoft.net/ugoira

if about the config key name, it should be ok because it is listed in `[Ugoira]` section?

`deleteZipFile` is only used in `handle_ugoira()`  https://github.com/Nandaka/PixivUtil2/blob/master/PixivDownloadHandler.py#L418 and `process_ugoira_local()` https://github.com/Nandaka/PixivUtil2/blob/master/PixivImageHandler.py#L530 so it shouldn;t affect other download

**Comment by NHOrus** [comment]
No, I mean when we convert ugoira to webm/apng we don't write name of new file into Downloaded list

**Comment by Nandaka** [comment]
ah, you talking about the text file created when `createDownloadLists = True` in the config.ini?

Maybe named it to `appendToDownloadedList` in `[Ugoira]` section?
