### ISSUE TITLE
Did anybody else notice a lower rate limit on Pixiv?

### ISSUE THREAD

**Issue by PatrickL546** [Nandaka/PixivUtil2#1157]
I just noticed I get "HTTP Error 429: Too Many Requests" as low as running 5 instances. Before I can run as many as my pc can handle.
Looks like they cut the request limit by a lot. Fanbox doesn't seem to have lowered its rate limit.
This is quite bad, I'm gonna try out a higher download delay.

Also, when it hits an error 429, it just moves on to the next image, Is there a way to get it to retry until it succeeds?

![image](https://user-images.githubusercontent.com/75874561/188298668-031da788-0de7-47e5-bdc3-1d11b2390175.png)

**Comment by Toyem** [comment]
This is what other users have also noticed there #1144 . Pixiv seems to have reduced the number of connections allowed per IP or something like that.
But because an error 429 means that the client made too many request to the server, trying endlessly to get the page until you have a successful response doesn't seems like the best idea (except if you want to get your IP permanently ban ^^')

**Comment by cglmrfreeman** [comment]
5 _instances of PixivUtil2_? Why?

**Comment by PatrickL546** [comment]
> This is what other users have also noticed there #1144 . Pixiv seems to have reduced the number of connections allowed per IP or something like that. But because an error 429 means that the client made too many request to the server, trying endlessly to get the page until you have a successful response doesn't seems like the best idea (except if you want to get your IP permanently ban ^^')

I was thinking of retry x time with x delay, instead of 1 error and skipping it like what it does now. I tried using the 
``retry = 5``
``retryWait = 10``
but it doesn't seem to be affecting the ones that get error 429.

> 5 _instances of PixivUtil2_? Why?

Cause it's faster :D

**Comment by cglmrfreeman** [comment]
> Cause it's faster :D

Please see #477 :grimacing:

**Comment by Toyem** [comment]
> I was thinking of retry x time with x delay, instead of 1 error and skipping it like what it does now. I tried using the
> `retry = 5`
> `retryWait = 10`
> but it doesn't seem to be affecting the ones that get error 429.

I don't know if doing retries will really help.
When a user gets an error 429, it usually means that the user has reached or exceeded his request quota for a certain period of time.
To get successful requests from the server again, you'll have to wait a little while until the server resets the request counter. So doing additional retries after receiving a 429 is not necessarily recommended because it can be totally counterproductive.
In any case it 's strange that despite your parameters the script don't do any retries. I don't know if this is intentional or not.

**Comment by PatrickL546** [comment]
> > I was thinking of retry x time with x delay, instead of 1 error and skipping it like what it does now. I tried using the
> > `retry = 5`
> > `retryWait = 10`
> > but it doesn't seem to be affecting the ones that get error 429.
> 
> I don't know if doing retries will really help. When a user gets an error 429, it usually means that the user has reached or exceeded his request quota for a certain period of time. To get successful requests from the server again, you'll have to wait a little while until the server resets the request counter. So doing additional retries after receiving a 429 is not necessarily recommended because it can be totally counterproductive. In any case it 's strange that despite your parameters the script don't do any retries. I don't know if this is intentional or not.

I'd just wanted to retry after 10min, or maybe an hour after an error 429. I've seen it clear up after a couple of minutes, instead of it getting skipped.

**Comment by Toyem** [comment]
> I'd just wanted to retry after 10min, or maybe an hour after an error 429. I've seen it clear up after a couple of minutes, instead of it getting skipped.

I understand what you want to do and I can see why you think this is a feature that might be interesting to implement. 
But I don't feel confident enough to modify the code in a way that can lead users of the script having their account being temporarily or (in extreme cases) permanently banned.
Manipulating these particular errors can be a dangerous game and I'd rather not play with that right now, especially since we see that Pixiv is changing their settings (you saw it yourself x) ).

**Comment by PatrickL546** [comment]
I'm probably just gonna slow down by a lot. Also made a backup account to download from there, just in case.
