### ISSUE TITLE
what error is this

### ISSUE THREAD

**Issue by rdegted** [Nandaka/PixivUtil2#1169]
Error at process_tags() at page 4: (<class 'TypeError'>, TypeError('the JSON object must be str, bytes or bytearray, not NoneType'), <traceback object at 0x040DE168>)
Dumping html to: Error page for search tags %E3%83%AD%E3%83%AA at page 4.html

Unknown Error, please check the log file: (<class 'TypeError'>, TypeError('the JSON object must be str, bytes or bytearray, not NoneType'), <traceback object at 0x00D84F08>)

Please answer in easy words so that Google Translator can translate it into Korean

**Comment by Toyem** [comment]
We lack some context to understand the source of the error.
Can you add to your comment the log file `pixivutil.log` to try to find the origin of your error? 
This log file should be in the same place as the script files.

**Comment by rdegted** [comment]
[pixivutil.log](https://github.com/Nandaka/PixivUtil2/files/9630556/pixivutil.log)

Is this enough?

**Comment by Toyem** [comment]
I was able to reproduce your error.
The problem you have seems to be related to an update from Pixiv on their query quotas. 
The time needed between two requests was increased a few weeks ago by Pixiv. Also, when searching for an image by tag (which you did), there is no waiting time between two requests.
This led to the error you had because you probably received a 429 error (Too many request) from Pixiv even if it doesn't appear in the logs.

**Comment by Toyem** [comment]
Ok Yuki fixed it with its last commit, it should be fine 👍
