### ISSUE TITLE
NoneType

### ISSUE THREAD

**Issue by rvtis** [Nandaka/PixivUtil2#1207]
Traceback (most recent call last):
  File "PixivBrowserFactory.pyc", line 488, in login
TypeError: 'NoneType' object is not subscriptable
Error at login(): (<class 'TypeError'>, TypeError("'NoneType' object is not subscriptable"), <traceback object at 0x040788E8>)
Error at doLogin(): (<class 'TypeError'>, TypeError("'NoneType' object is not subscriptable"), <traceback object at 0x04418F88>)
Cannot Login!

Have python 3.8 and ffmpeg, using executable

**Comment by marisukukise** [comment]
I had a similar problem (not sure if the exactly the same one), but I solved it by using my login, password and cookie value in config.ini
Q3 in https://github.com/Nandaka/PixivUtil2#a-usage

**Comment by Hecatom** [comment]
> I had a similar problem (not sure if the exactly the same one), but I solved it by using my login, password and cookie value in config.ini Q3 in https://github.com/Nandaka/PixivUtil2#a-usage

I am having the same issue, and I already do that.
I pressume that is maybe related to me using a VPN, the problem is that not using the VPN is an imposibility in my case, since for some reason the ISP I have is unable to connect to sites like Pixiv, Imgur and others for no other reason than who knows, but using a VPN like expressvpn which is the one I use has worked fine for me until yesterday.

So, now I am stuck unable to access the site with PixivUtil, while just browsing the site doesn't yield any kind of problem.

Funny enough, I can access fanbox without any problem without a vpn, but pixv, nope.

**Comment by Nandaka** [comment]
dupes with #1209
