### ISSUE TITLE
请求教程和帮助😭

### ISSUE THREAD

**Issue by oinlikejser** [Nandaka/PixivUtil2#1242]
### Prerequisites

* [ ✅] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [ ✅] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [✅ ] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

[我是一个代码新手，不会操作，请求您录制一个视频教程，教我怎么才能使用pixivuntil2，非常感谢🫶]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [希望您能录制一个视频教程，如何安装并使用pixivuntil2]

**Actual behavior:** [您只有一些代码解释和文字叙述，有很多专业术语，对于普通人来说看不懂😢]

**Log file:** [Attach the `pixivutil.log` file in the application folder, recommended to delete the old file, reproduce the issue, and upload the newly generated file here]

### Versions

You can get this information from executing `PixivUtil2.py --help`.
Latest version available in https://github.com/Nandaka/PixivUtil2/releases

**Comment by dragontamer8740** [comment]
My suggestion is that you download it:
https://github.com/Nandaka/PixivUtil2/releases/latest

I also suggest that you log in using https://github.com/Nandaka/PixivUtil2/wiki#pixiv-login-using-cookie to guide you.


English (not a direct translation, but close enough):

Title: Requesting Help and a Tutorial

I don't know how to program; please make a video showing to teach me how to use PixivU(n)til2. (sign language heart)

Expected behavior:
I want a video showing me how to install and use PixivU(n)til2.

Actual behavior:
There are only textual and code-based descriptions with a lot of technical terms that I don't understand

(Actually they said "that regular people can't understand." I changed it.)

**Comment by oinlikejser** [comment]
@dragontamer8740 谢谢你回答我，我会努力研究

**Comment by Nandaka** [comment]
@oinlikejser There is still an issue with the login due to Cloudflare change something and always return 403 Forbidden error.
Some people have success by modifying the configuration mentioned here: https://github.com/Nandaka/PixivUtil2/issues/1241#issuecomment-1450739469

**Comment by photonometric** [comment]
@oinlikejser If username/password/PHPSESSID cookie are setup correct in the config.ini file, then you probably just need to change the `useragent =` line to:

`useragent = Mozilla/5.0` 

It is the login problem most people are having right now (for instance #1245)
