### ISSUE TITLE
Option to allow duplicate downloads between member and tag searches

### ISSUE THREAD

**Issue by cr08** [Nandaka/PixivUtil2#127]
Subject TL;DR. Unless there's a config setting I have missed. More often than not I have images that exist between member and tag lists but currently it will only download a given image from one source and ignore the other. It'd be awesome to be able to allow this.

**Comment by Nandaka** [comment]
Assuming you download the image to different folder, try to set:

```
overwrite = True
alwayscheckfilesize = True
```

in config.ini

**Comment by chronometric** [comment]
This was discussed in #107, and the solution there was to allow various config options by which to specify alternate config.ini and db files.

Sounds like a more sophisticated/simplistic option became available at some point. So...using the same database, and checking the file size, the program will overwrite [its null option]? 

I'm a little dense tonight, but I'm a bit confused by how overwrite interacts with the file size check...just to confirm, if I run multiple searches or searches of different kinds, **these two options will have the same effect as though the database was unaware of previous downloads?** The alwayscheckfilesize option always confused me, lol ^^;;;

_Very glad to see you're still active on Github. Transferring your blog to the Dutch blogger might work, since nothing on pixiv violates Dutch law, and *ahem* a group I'm aware of has run a small translation blog there without harassment for a good 4 years now. There are also a few reliable and fairly inexpensive Dutch web sites that don't mind adult content of this type. Not that you need one, but just letting you know about an option._

**Comment by Nandaka** [comment]
- overwrite and alwayscheckfilesize = False
if already exists in DB, skip download.

- overwrite = True, alwayscheckfilesize = False
always download even file exists in DB and the target file path.

- overwrite = True, alwayscheckfilesize = True
always download, except file already exists in target file path with the same size.

- overwrite = False alwayscheckfilesize = True
no impact, similar with 1st behaviour.

**Comment by panhartstuff** [comment]
@Nandaka Is this outdated information?

- overwrite = True, alwayscheckfilesize = True
This will check the filesize if file already exists in target file path, but it will overwrite even if the filesize matches.

- overwrite = False alwayscheckfilesize = True
This will check the filesize, but it will NOT overwrite if the filesize match. This will ignore the DB, so it's not similar with the 1st behaviour.

**Comment by Nandaka** [comment]
should be like this:
```
if both overwrite and alwaysCheckFileSize disabled:
  It will skip if localfilename exists.
else:
  # local file check  
  if overwrite is disabled:
     skip if local size and remote size match.
  # db check filename
  if overwrite is disabled:
     skip if local size and remote size match.
```
