### ISSUE TITLE
Pixiv Overuse Help?

### ISSUE THREAD

**Issue by connerbanner** [Nandaka/PixivUtil2#1317]
I've been using this program for years now and I've just got my first overuse warning from Pixiv. Is there anyway for me to mess with the settings so I can have an easier time slipping under their radar? I dont mind slower download times at all, i just want to make sure all my follows are being downloaded. Or any advice regarding overuse on pixiv would be very helpful, like should i download at a time when its not busy or how long i should wait till downloads?

**Comment by PorkeyThePine** [comment]
In your config file, you can increase
`downloadDelay`
 to a higher number
`retry`
`retryWait`
may also help.

**Comment by PatrickL546** [comment]
Set `downloadDelay=5`

**Comment by connerbanner** [comment]
Ive set all 3 things above to 5 and will keep a close eye on it for now.

**Comment by connerbanner** [comment]
all right, it looks good but good lord is it taking forever, but that's the price I must pay, thanks for the help.

**Comment by Ikkoru** [comment]
Additional info (2025.05.03):
Got a warning email from Pixiv after setting PixivUtil2 to check all of my files to find and redownload the missing ones.
Received the warning approximately 40 hours after starting up the program. Around 69420 files were checked in that time. I don't know how many of them were redownloaded.
Used downloadDelay = 5.

Suggestion to users:
In case you need to download or check **very** many files, it would probably be safer to run the program several times over a number of days or even weeks.

I would estimate that it is safe to check 42069 files in 24 hours. The user should then wait a day or two, or three before resuming.
Due to file count being an inconvenient measure, a safe-ish alternative would be to only download 42 full accounts in a day before waiting.
