### ISSUE TITLE
add filter to stop pixivutil2 bulk downloader from downloading child art so that it only downloads the adult anime art work only. to protect uk users this is needed very badly.

### ISSUE THREAD

**Issue by aurimilky** [Nandaka/PixivUtil2#1330]
there is a big problem with pixivutil2. yes it works fine. that is not the problem. as you know lots of people are using pixivutil2 in the world to bulk download from pixiv which is fine. now i know that anime artist love to create any anime art. problem is if that anime artist has a child in it even if rest of anime art work is adult anime art work. uk is using it to hack in to peoples computers that are bulk downloading anime. is there any chance of adding a filter that stops anime art that has child from being downloaded so that bulk downloader can only downloads the adult anime art work only? so it stops people in the uk that are using pixivutil2 from getting into trouble.

many thanks
ashton

**Comment by biggestsonicfan** [comment]
This is a Pixiv issue, not a PixivUtil2 issue. Pixiv [actively complies with local laws](https://www.pixiv.help/hc/en-us/articles/26578893289881-I-can-t-browse-certain-works-from-the-country-region-where-I-live), as such, countries like the United States can not view "child art". You can change your user preference's "Country/Region" to "United States" where "child art" is already restricted, but I am sure "United Kingdom" will get the same restrictions if they aren't already in place.

Otherwise you can do the following:

1. Set the Viewing Restrictions "Explicit content (R-18)" and "Ero-guro content (R-18G)" to "Hide"
2. You need to [mute the tags you don't want to see on your account](https://www.pixiv.net/setting_mute.php). It is also a premium paid feature.
3. In the [[DownloadControl]](https://github.com/Nandaka/PixivUtil2?tab=readme-ov-file#downloadcontrol) setting of settings.ini, change `useblacklisttags` to `true` and create a file `blacklist_tags.txt` with all the "child art" tags.

**Comment by NHOrus** [comment]
Ah, person who can't distinguish reality from fantasy and actual people from imagined.

**Comment by aurimilky** [comment]
> This is a Pixiv issue, not a PixivUtil2 issue. Pixiv [actively complies with local laws](https://www.pixiv.help/hc/en-us/articles/26578893289881-I-can-t-browse-certain-works-from-the-country-region-where-I-live), as such, countries like the United States can not view "child art". You can change your user preference's "Country/Region" to "United States" where "child art" is already restricted, but I am sure "United Kingdom" will get the same restrictions if they aren't already in place.
> 
> Otherwise you can do the following:
> 
>     1. Set the Viewing Restrictions "Explicit content (R-18)" and "Ero-guro content (R-18G)" to "Hide"
> 
>     2. You need to [mute the tags you don't want to see on your account](https://www.pixiv.net/setting_mute.php). It is also a premium paid feature.
> 
>     3. In the [[DownloadControl]](https://github.com/Nandaka/PixivUtil2?tab=readme-ov-file#downloadcontrol) setting of settings.ini, change `useblacklisttags` to `true` and create a file `blacklist_tags.txt` with all the "child art" tags.

thanks

**Comment by biggestsonicfan** [comment]
@aurimilky As an update, Pixiv is now blocking all R18 rated works int he UK, including "child art" so just keep your region set to UK and you should be fine.
