### ISSUE TITLE
Request APNG Merge function for Animat image

### ISSUE THREAD

**Issue by pokiller** [Nandaka/PixivUtil2#149]
I am not sure if you know this software: PxivAnimatDownloader.
It could download Animat images as ZIP file, or merge them into a GIF or APNG file.
It would be so nice if you can include such function in your program :D

**Comment by Nandaka** [comment]
only gif is supported.

**Comment by pokiller** [comment]
Eh, the true is, I want images in loseless format...
I am not a programer, so maybe you can try this software and see if you can add more features on yours XD.
Links here: https://app.box.com/s/b8msix7up2uhb6tqtaxgdu9n6qf2oepr

**Comment by Nandaka** [comment]
If you want to use lossless format, the better keep the ugoira file and use http://www.bandisoft.com/honeyview/ to view it.

**Comment by chronometric** [comment]
I wasn't aware of the conversion issue, but was just catching up on some of the previous work in the area....

- [https://neregate.com/blog/2015/09/20/tutorant-how-to-save-ugoira-pictures-from-pixiv/?replytocom=228388#respond](Yuki's browser bookmarklet) that saved whatever the original images were
- [https://greasyfork.org/en/forum/discussion/7410/pixiv-ugoira-webm-online-conversion-rules-added?new=1](greasemonkey script) to convert to APNG or WebM
- Even some more [https://www.reddit.com/r/webm/comments/2ubr93/convert_images_to_webm/](movie-like) WebM converters.

Personally I would like to see APNG as well, since GIF is basically the worst we have and is only still a thing because it's animated. Are you saying that none of the previous tools work to save the original zipped images? Or does that encryption get in the way of conversion? Or does conversion depend too much on clunky UI software?

Two years ago, the kids on Bandisoft's Honeyview forum were [https://forum.bandisoft.com/viewtopic.php?f=23&t=3306](https://forum.bandisoft.com/viewtopic.php?f=23&t=3306)putting all their hopes in PixivUtil finding an elegant solution to this awkward problem. Is there not some way that, being able to get to GIFs as we do, we cannot convert to PNG instead?

**Comment by Nandaka** [comment]
set ```createugoira = True``` in config.ini, it will create .ugoira file, which can be opened in honeyview.

basically .ugoira is a zip file with animation metadata inside.

**Comment by chronometric** [comment]
> basically .ugoira is a zip file with animation metadata inside.

Sure! My understanding is that it is something like a slideshow more than film, with the JS able to manipulate things like freeze-frames on the millisecond level. 

I just unzipped one of the .ugoira files I downloaded today, and it's a series of 154 small JPEGs with 24 bit color depth. I think the reason we (and everyone) wants APNG is because it's another common format that supports GIF-like animation, conversion from other files like JPEG would be lossless in terms of detail, and is capable of representing truecolor in either 24 or 48 bits. GIF's paltry 255 colors, besides the obvious loss of detail when losing the color depth, can easily create gradient tears in anime/manga-style drawings.

You know all this....so what I'm wondering is, with a .ugoira full of JPEGs or PNGs and a JSON file telling each one when to flick....why are the current GIF animation converions possible, while you seem to be saying that conversion to a largely superior file format is only possible inside the viewer software?

**Comment by Nandaka** [comment]
> current GIF animation converions possible

because there is a library supporting the conversion (imageio) from individual image to gif, and apng is not that common. Unless there is a python library that can convert individual images to apng, then I might give a shot.

**Comment by chronometric** [comment]
Hmm, let's see. Actually [FFmpeg can do it](http://trac.ffmpeg.org/wiki/Create%20a%20video%20slideshow%20from%20images), though perhaps not with the control necessary to decode the JS files? 

I'm not sure what kind of library would work for you; there's quite a bit of overlap between PNG and APNG (or more properly, MNG), because MNG is really just a wrapper for PNG files. This page is [overflowing with technical information which might help you](http://www.libpng.org/pub/mng/), though I think the practical answer will be on the [Libraries and Toolkits page](http://www.libpng.org/pub/mng/mngaptk.html), with many libraries combining what seem to be the basics of PNG with some "video"control. 

FreeImage has had libMNG it built-in since v2, though in 3.15.2 they removed dependency so the library could handle it internally [like this?](http://freeimage.sourceforge.net/fnet/html/13350E8B.htm).

Not sure if any of that catches your fancy, but might be worth looking over to help everyone retain their porn colors ;3

**Comment by Nandaka** [comment]
Well, I don't call the freeImage dll directly, as I'm using imageio feature.
https://github.com/Nandaka/PixivUtil2/blob/master/PixivHelper.py#L642

**Comment by Nandaka** [comment]
ok, found the library for apng,

> APNG support via Pillow https://pypi.python.org/pypi/apng/0.1.0

**Comment by Nandaka** [comment]
set ```createApng=True``` in config.ini.

Note: the generated png is not optimized due to library limitation.
