### ISSUE TITLE
Conversion of existing ugoira files?

### ISSUE THREAD

**Issue by chronometric** [Nandaka/PixivUtil2#158]
I love the new conversion feature (implemented #135). I wonder if it would be possible to have an option for this conversion to take place any time the program encounters a ugoira file on disk? I could delete and re-download, but that's not nearly as elegant if you can add this in easily.

Thanks as always :3

**Comment by Nandaka** [comment]
might be a little bit tricky, as the js file might be not available. I'll see what I can do.

**Comment by vampiricwulf** [comment]
Rather than programming it into PixivUtil2, wouldn't it be easier to write an accessory tool that would recursively search a directory for things with *.zip or *.ugoira matching the filenameformat's config, create a list of those files, then have a special skip of the download process in PixivUtil to start execution of the conversion process?

**Comment by Nandaka** [comment]
should be, if you know python, you can call the method defined below to convert .ugoira to .gif

https://github.com/Nandaka/PixivUtil2/blob/master/PixivHelper.py#L645

**Comment by Nandaka** [comment]
updated in the latest commit.

if CreateUgoira/CreateApng is enabled, it will check the ugoira file exist and no existing gif/png file
