### ISSUE TITLE
Duplicated download when artist change his name

### ISSUE THREAD

**Issue by eromoe** [Nandaka/PixivUtil2#169]
Hi,  I found there is a problem when choose `5. Download from online user bookmark`. It would duplicated download artist  when his name change:
first two and last three are duplicated 
![qq 20161113123841](https://cloud.githubusercontent.com/assets/3938751/20243706/48af2f58-a99e-11e6-8395-e66132e5bee3.png)

I suggest detect id first. 
For example,  search the download folder, if there is a folder name `xxx (artist_id)`, then use this folder. This is the most easy way to avoid duplicated download.

**Comment by Nandaka** [comment]
You can use `%member_token%` instead `%artist%` as it doesn't check the folder name (might result false positive)

**Comment by eromoe** [comment]
But I'd like to see artist name as part of folder , it is more intuitive than `%member_token%`

**Comment by Nandaka** [comment]
I have no plan for folder detection.

Also, it should skip already downloaded images

https://github.com/Nandaka/PixivUtil2/blob/master/PixivUtil2.py#L699
https://github.com/Nandaka/PixivUtil2/blob/master/PixivUtil2.py#L507

**Comment by whinette** [comment]
I'm working on a python script that will resolve this (and some others dupe problems I have). It's still a wip but the merging of these users is done.
It will need some rework as we're not using the same structure and I did not wrote it will public release in mind, so it's pretty much hardcoded to my needs.

https://github.com/whinette/pixixDownloader_cleaning

@eromoe 
You only need to edit line 71 (change 'Pixiv' to '.' and put the script in the folder where all the users are) and rework the regex on line 32 with this one that should do the trick '\s.+\((\d+)\)$'

Cheers.

**Comment by Deejay85** [comment]
This probably isn't going to be to your satisfaction if you like to have named "named" folders, but since the majority of what I got is in Japanese, and since I can't read Japanese, the artist's name is only there as decoration as far as I'm concerned. Yes...I would prefer to keep it, but I am okay if I have to do without. What I did was change the following in the config file to the following

filenameformat = %member_id%\%urlFilename% - %title%
filenamemangaformat = %member_id%\%urlFilename% - %title%

What this will do is skip the artist's name entirely, leaving only the member ID, and as a result of this, no matter what they may change their name to, the folder their work is kept in remains the same. Yes...trying to find a particular artist may be a pain if the username is in English, but since I can't read what 鬼麿 (681163) is supposed to be, and since it is going to get lost anyway in the sea of other artist's IDs, why worry?

**Comment by eromoe** [comment]
I created a fork to solve the problem. https://github.com/eromoe/PixivUtil2

@Nandaka I tried my best to touch as less files as in PixivUtil2, only affect `PixivHelper.py` , but due to restriction of my code, I think it can't simply merge into main branch . So I don't open a PR.
And I think there is a design issue in filename generation.  Now, PixivUtil2 construct full path with folder and filename by one function . I think it better split into two parts,  create folder first(save to db) , then determiner the filename when download it.
