### ISSUE TITLE
[Enhancement] Config option alwaysCheckFileExists

### ISSUE THREAD

**Issue by awiebe** [Nandaka/PixivUtil2#299]
Right now there is an option ```alwaysCheckFileSize``` which is helpful for checking file integrity, but no flag for just checking if a file exists.

Sometimes pixiv assumes a  file exists, but this can be overridden with ```alwaysCheckFileSize``` for example this is the solution proposed for https://github.com/Nandaka/PixivUtil2/issues/274- but if you **don't want to ask the pixiv.net servers about the size of each checked image**(network operations are the slowest type of file access) **you just want to check if files that claim to be downloaded have been downloaded**, you can't do this at the same time as downloading you have to "clean the database".

**Comment by NHOrus** [comment]
I think for that you either need to donate to Nandaka or write it yourself

**Comment by Nandaka** [comment]
most likely I will change the behaviour of `alwaysCheckFileSize` to check if the local file exists or not first, rather than adding new flag.

e.g.
1. check local file exists.
2 if yes, get remote file size, else download the image.
3. if got size difference, download the image, else, skip downloading.
