### ISSUE TITLE
[Feature Request] Option to download avatars in tag-specific modes

### ISSUE THREAD

**Issue by riQwn** [Nandaka/PixivUtil2#390]
### Prerequisites

* [x] Did you read FAQ section?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

I only want to download images with specific tags, so I'm usually unable to download only by member id; however, despite the avatar url being fetched in other modes as well, the member avatar only currently seems to be downloaded in mode 1 `Download by member_id`.
Other modes I tried out without success: 2, 7, 10

### Versions

PixivUtil20180726

**Comment by Nandaka** [comment]
Avatar is only download by using option 1. This is by design.

It doesn't make sense to enable for other modes, as it just will create a clutter of avatar images (if the filename is unique) or it just will overwrite the current avatar filename in the current folder (by default, it will uses folder.jpg).

**Comment by riQwn** [comment]
Fair enough, but wouldn't it at least make sense to also download the avatar with option 10 seeing as it's basically a filtered version of option 1?
The cluttering or overwriting would happen in either case, if you were to redownload by member id.
