### ISSUE TITLE
Restricted Fanbox content

### ISSUE THREAD

**Issue by Jmbkpo** [Nandaka/PixivUtil2#452]
### Prerequisites

* [Y] Did you read FAQ section?
* [Y ] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description
I am able of downloading from a Pixiv Fanbox  post that is unavailable for me? for not being a patron. I am searching about and i couldn't find a response, plus i don't understand nothing of code so this is hard for me.
[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

You can get this information from executing `PixivUtil2.py --help`.

**Comment by NHOrus** [comment]
No, only things that artists put in public or you got by being a patron.

Отправлено из Yahoo Почты для Android 
 
  чт, 20 дек. 2018 в 7:33 Jmbkpo<notifications@github.com> написал(-а):   
Prerequisites
   
   - [Y] Did you read FAQ section?
   - [Y ] Did you test with the latest releases or commit ?

Description

I am able of downloading from a Pixiv Fanbox post that is unavailable for me? for not being a patron. I am searching about and i couldn't find a response, plus i don't understand nothing of code so this is hard for me.
[Description of the bug or feature]

Steps to Reproduce
   
   - [First Step]
   - [Second Step]
   - [and so on...]

Expected behavior: [What you expected to happen]

Actual behavior: [What actually happened]

Versions

You can get this information from executing PixivUtil2.py --help.

**Comment by Jmbkpo** [comment]
Thanks, sorry.
