### ISSUE TITLE
Pixiv Fanbox Question

### ISSUE THREAD

**Issue by LuckySPixiv** [Nandaka/PixivUtil2#604]
Hello Nandaka, I was testing PixicUtil2 and found this:https://github.com/Nandaka/PixivUtil2/issues/402
I look into it, but I can't really get anything from fanbox other than the preview of the real image. I don't know if this program can get the real image or manga itself since looking into the issues #402  since some screenshot looks like it shows the real image other than the preview. If you want to state anything that is wrong or what this program can or can't do, do so since I'm looking for images of a creator I really liked. I'll show screenshot if you want.

**Comment by bluerthanever** [comment]
Hey. Where did you get the preview of the real image? I have been using this great util a long time, and it works perfectly. Maybe you are using the wrong function like downloaded pictures from pixiv.net, instead of pixiv.net/fanbox.
If so, try using the functions starts with an "f", like f1 and f2. But make sure that the creator is in your supporting list and that the post is visible to you.

**Comment by YerALizardHarry** [comment]
Hey I have a quick question fanbox, specifically about download directories. 

How can I separate the primary pixiv gallery and fanbox gallery of the same artist into different download paths? I dont really want everything to be mixed together in one folder based on member ID.

**Comment by NHOrus** [comment]
You need two different `config.ini` with different path directives.
