### ISSUE TITLE
Able to download from pixiv but unable from fanbox, OAuth failed, no refresh_token got.

### ISSUE THREAD

**Issue by mo-han** [Nandaka/PixivUtil2#631]
### Prerequisites

* [x] Did you read FAQ section?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

Latest version (PixivDownloader2 version 20200125 - Happy CNY 2020!).
PHPSESSION set in config.ini `cookies`.
Already supported the targeted artist on FANBOX.
Using same proxy for both pixiv and FANBOX connecting.
Able to download pictures from pixiv without issue.
Unable to download from FANBOX.
Failed to login using OAuth when try downloading from FANBOX.
Never get a `refresh_token` in config.ini and that item always being empty.

**Comment by mo-han** [comment]
```
103:pixiv ID、またはメールアドレス、パスワードが正しいかチェックしてください。
1508 Failed to login using OAuth, hasDumpPage=N, pageData=None
```

**Comment by Nandaka** [comment]
do you key in the username/password in the config.ini? the error message from pixiv said you keyin wrong username(email) or password.

**Comment by Horatio-h** [comment]
use your email as the username instead of your nick.

**Comment by mo-han** [comment]
I tried email, nickname, and empty '' (current value). All failed.
BTW, is there anything with refresh_token?

**Comment by Starkiller0225** [comment]
Sorry, but can I download the locked images from unsupported FANBOX artist?

**Comment by Nandaka** [comment]
@Starkiller0225 Nope, it is using Pixiv API so it will follow based on your subscription.

**Comment by theChrisliebaer** [comment]
Having had the same issue I would like to confirm that using the email instead of the Username does in fact resolve the problem on my end. Note that I'm not the original author of this issue.

The steps I used to resolve the issue:

1. Set `username` to my email
2. Set `password` to my actual password
3. Leaving `cookie` and `refresh_token` empty. Resulting in a CAPTCHA response.
4. Copying `cookie` from a fresh browser session I created in inkognito mode.
5. Restarting PixivUtil2, confirming successfull login and successfull download of fanbox content
6. Oberserve that `refresh_token` was automatically set and a login notification mail was sent to my inbox.
