### ISSUE TITLE
Write relative path to image in HTML

### ISSUE THREAD

**Issue by rwchunk** [Nandaka/PixivUtil2#669]
### Prerequisites

* [x] Did you read FAQ section?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

Thanks for implementing the HTML download feature, it works as expected and I really appreciate it.
The only thing is that the HTML file uses absolute paths to locate images.
Therefore, if I moved my collection, all the links would break within the files. Please switch to writing relative paths, or provide an option. Then this feature would be perfect.

Is it possible to download the HTML/image to separate locations? If not, then relative paths are simply at the root.... But having images in a subfolder from the HTML sounds nice though.

### Versions

~v20200404-beta2

**Comment by bluerthanever** [comment]
Sorry I didn't come up and check regularly, thus the late reply.
Hmm... actually I have thought about that when I was writing this... I guess I just chose the easier way. Haha.

Did you mean that, if the html files could be saved to a different location then relative path would be needed no more?  If so, you can just move your html anywhere you want without caring where the images are. Unless you also want to move the images.

Or if you want to move both the html and images, then relative path only works when you keep their relative structure, because the relative paths is defined by the location where the html file is at, not just the root path, in my understanding.

Or if you want to move them without caring about their relative positions, I think that would be impossible?

Please describe the way you want it to be, or how you move your files. Thank you very much.

**Comment by bluerthanever** [comment]
Sorry I didn't come up and check regularly, thus the late reply.
Hmm... actually I have thought about that when I was writing this... I guess I just chose the easier way. Haha.

The good thing about absolute paths is that you can move the html files freely, on condition that your images stay where they are.
But relative paths are defined by the location where the html file is at, not just the root path, in my understanding. So even if the paths are changed to relative paths, when you want to move them, you have to keep their relative structure, which I guess means that you have to move them at the same time.

Whichever way wouldn't allow you to move whichever file wherever you want them to be, otherwise I think it's better to just make another separate tool to help you view the files.

Please describe the way you want it to be, or how you move your files. Thank you very much.

**Comment by rwchunk** [comment]
I don't mind. Thanks for taking your time.
In my case, and by the default setting, works are organized into folders per-artist. The only times I have needed to move files around, I move the artist folder as a whole, or the collection as a whole.
When I browse regular works, I access them on a per-artist basis as well. Basically, files are already sorted in a way that the html would be moved around with the images.

If I had an system for indexing and browsing, I could simply build around this and regular, non-fanbox works would be sorted this way as well. Not that I know of such a system.
If I wanted to do it right now, I could dump a bunch of HTMLs into a folder, and dynamically create an index simply by reading the contents of that folder. That is a possible use case, but it would be lacking regular works, which make up the majority of pixiv collections. I believe it would be ideal to browse fanbox and regular works together. It could probably also seek for html files as well instead of simply mapping a single folder.
Such a thing is beyond the scope of pixivutil. But for those purposes, using relative paths and stricter organization _shouldn't_ be a problem. At least, as far as I can see it.

**Comment by bluerthanever** [comment]
Thanks for the explanation. If you can make sure you move the HTMLs and images as a whole, then relative paths would be no problem.
And one thing about the "dumping a bunch of HTMLs into a folder, does this mean, you still want to have a `htmlfilenameformat` in config and save all the HTMLs by that format? Because if not, when you move all the HTMLs into one folder (which means HTMLs only to me) might not keep its relative position to images, I am afraid. Sorry to be revolving about the relative position thing all the time, but it's kinda crucial and defines whether the HTMLs work after the change when you move your files.

**Comment by rwchunk** [comment]
Oh no, I only meant that hypothetically in consideration of absolute paths.

**Comment by bluerthanever** [comment]
Hmm. So can I take that as "changing things to relative paths is enough"?

**Comment by rwchunk** [comment]
For the most part.
My other intention was that I want to have it download to a structure like this:
`artist/item1.html`
`artist/item1/item1_00.jpg`
to make it a bit cleaner.

**Comment by bluerthanever** [comment]
Hmm. That, I think could be achieved with changing the filename format?
Like, currently, there are 4 types of formats for downloaded files(not including avatars):  `filenameFormat`, `filenameMangaFormat`, `filenameInfoFormat`, `filenameMangaInfoFormat`.
I think when it comes to FANBOX posts:
 - for post cover it uses `filenameFormat`
 - for images inside posts it uses `filenameMangaFormat`
 - for info, and html uses filenameInfoFormat
So I guess what you want could be like:
filenameInfoFormat = %artist_id%/%image_id%
filenameFormat = %artist_id%/%image_id%
filenameMangaFormat = %artist_id%/%image_id%/%urlFilename%
or other syntax, you got the idea. I myself prefer using ids, you can use %artist% or %title% if you want to.

You can go giving it a try. I'll start working on the codes.

**Comment by bluerthanever** [comment]
#671

**Comment by rwchunk** [comment]
I achieved my desired result with
`filenamemangaformat = %artist% (%member_id%)\%image_id% - %title%\%urlFilename%`

**Comment by Nandaka** [comment]
@bluerthanever #671 merged.

**Comment by bluerthanever** [comment]
Yes. Thanks. =)
