### ISSUE TITLE
Question/Proposal - Image Info Writing - Consolidation?

### ISSUE THREAD

**Issue by jwshields** [Nandaka/PixivUtil2#710]
Hello!

I'm posting this as an issue because I wanted to validate my thinking here and gather some thoughts.

Right now in the settings, you can configure `writeimageinfo` & `writeimagejson` - 
Both of those settings are fine, but what I've found is that when writing these files, over time, it can introduce some large growth to the MFT if you're using NTFS. That isn't super good, but it's not inherently bad.
Context: NTFS stores "small" files (~1024K) in the MFT directly, rather than outside of it, as with "normal" files. Many small files in the MFT can cause it to balloon in growth and possibly fragment it. Along with some other potential performance issues
Links: https://www.sciencedirect.com/topics/computer-science/master-file-table & http://www.ntfs.com/ntfs-mft.htm

I was thinking..
Would it be worth changing the format here?
Introducing an option to build one larger json/txt file, instead of individual files for each image/manga?
Something like this: https://gist.github.com/jwshields/af8676d30a225d91dfb6a23c13b7eb7e

If it were to be introduced as an option like... 
`writeimageinfo = True|False`
`imageInfoFormat = text|json|both|combined` - both would be equivalent to writejosn=true & writeinfo=true - but I'm not sure the best word to use for what I'm proposing - combined/large/artist/single, thoughts?

Something like this would retain existing behavior, although change up the settings for it a small bit, but allow a larger/single info file to be used.

Would this be worth looking into? I was thinking of starting to implement it, but wanted to gather thoughts if this could be desirable before doing that

**Comment by Nandaka** [comment]
why not enabling compression on that folder?

**Comment by bluerthanever** [comment]
even though i don't really read those image info files, i think it would be too much work to look for the information of a specific image/manga in a big file rather than how they are stored now.
for me writing the files into a whole big file is not somewhat more convenient, and maybe i don't have that many small files to cause a big increase in the MFT sizes, so i don't really care....

and as the file gets bigger and bigger it would also be really difficult to even open it, let alone to search for something in it.

for me i would rather want it to be: 1. all image/manga information to be saved in a database (which takes care of your problem), 2. a tool to view local files + get information from database and display it along with the images, which might also be slow due to the size of the database maybe

**Comment by jwshields** [comment]
Closing issue,
been thinking more on this and I don't believe it's worth the time right now;
Thanks for the input though
