### ISSUE TITLE
[Feature Request] More Ugoira Format Options

### ISSUE THREAD

**Issue by HydroHydro** [Nandaka/PixivUtil2#718]
### Prerequisites

* [x] Did you read FAQ section?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

We already have gif, webm, and webp. Could we get support for a better video format like mp4? Or possibly more?

**Comment by Nandaka** [comment]
webm/mp4 is just a container, but you can tweak the ffmpeg settings in the config.ini if you want to adjust the compression.
Also, ugoira doesn't have any sound, so I don't think mp4 is useful here.

**Comment by HydroHydro** [comment]
The mp4 container is more widely used. For example, Apple's Safari browser does not support webm files.

**Comment by Nandaka** [comment]
hmm, maybe I can add an option for the target extensions.
https://github.com/Nandaka/PixivUtil2/blob/master/PixivHelper.py#L851

**Comment by photonometric** [comment]
MP4 might be nice since it's a 'proper' movie file format, and might have some compatability/playability advantages over the more awkward and web-oriented webm format.

That being said, movie players like MPC-HC and VLC can play webm files easily. So can every decent browser (so, not safari or MS edge). In practicality the main advantage of MP4 is probably recognizability, since webm isn't used by most people.

**Comment by Nandaka** [comment]
try https://github.com/Nandaka/PixivUtil2/releases
