### ISSUE TITLE
Can not download by tag/taglist after a while

### ISSUE THREAD

**Issue by foolydooly** [Nandaka/PixivUtil2#72]
I'm not sure if this is Pixiv bug or PixivUtil bug.

Basically, after downloading with PixivUtil for few hours I can't download any further.. Except by using image ID#, I can not download image. Downloading just halted. Changing tag does nothing. Deleting Database setting and starting fresh does nothing. (Does PixivUtil save temp file in Temp folder for Win-PC? Or no?)

Log shows no useful info, but I will dump it if needed.

**Comment by TheDoc69** [comment]
I have the same problem since yesterday. It seems that something changed on PIxiv yesterday and is impacting the download by tags (individually ou by tag list). It worked two days before, but now it stops immediately saying “No more images”, without downloading anything or any visible error. Download by member id or image id is ok. There is also no information in the log. 
Another information is that copy-pasting a tag search url (the one generated by pixivutil during the tag search) in a web browser works. So maybe pixiv changed something in their code ?

**Comment by 1idd0kun** [comment]
I'm having this problem, but in my case downloading by tag stopped working completely. The program responses with a  "no more images" message when I try do download by tag, with any tag. I tried with ナルヒナ (%E3%83%8A%E3%83%AB%E3%83%92%E3%83%8A). It didn't work so I deleted the database file and changed the download folder and tried again with the same tags. It didn't work either. Then I tried with 園智恵理 (%E5%9C%92%E6%99%BA%E6%81%B5%E7%90%86), which I didn't used before, but it didn't work either. I tried with other tags but I got the same response: "no more images." It doesn't matter if I previously downloaded from the tags or not. Not one worked.  

It was working okay on 22/03. I think it stopped working yesterday (23/03). I tried today and it still doesn't work. Perhaps pixiv chanced something in their website.

**Comment by Nandaka** [comment]
Most likely they changed the layout, so the application cannot see the images. I'll update it on the weekend

**Comment by TheDoc69** [comment]
Thanks ;)

**Comment by hatabbich** [comment]
thx man, your app really amazing!
