### ISSUE TITLE
QUESTION: How do I use this thing, in simplest terms for a total noob?

### ISSUE THREAD

**Issue by beanman911** [Nandaka/PixivUtil2#728]
### Prerequisites

* [ ] Did you read FAQ section?
* [ ] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

I don't know anything about coding but when I run windows command inside the folder, and try to use the commands like "-s b" for batch download or even "-h" for help I get errors. Can someone explain to a simpleton how to run this program? Thank you so much in advance

P.S. trying to batch download from my bookmarks page!

**Comment by thegreatestminer** [comment]
This tutorial assumes that you have done the following:
- You have the latest version of Python installed. (3.8.3 as of this post)
- You cloned the repository instead of downloading a release.
- You use Google Chrome as your browser of choice.
- You are also logged into pixiv.net on said browser.

What you want to do is open up a command prompt in the PixivUtil2-master folder, and then run `pip install -r requirements.txt`. This will install all of the prerequisites for PixivUtil2 to run. Once that finishes, you can now run `python PixivUtil2.py` to start the program. It will ask for your Pixiv username+password, and then it will fail on a reCAPTCHA error.

Now, open up config.ini in your text editor (please, no word processors.) and navigate to Line 60. Now go to pixiv.net on your browser, then click on the lock icon to the left of the browser. Now click on the Cookies menu, shown here:

![image](https://user-images.githubusercontent.com/19188146/84921975-31c69380-b093-11ea-9955-6786e118102c.png)

Now open up `pixiv.net`, `Cookies`, then click on `PHPSESSID`. Double click on the "Content" value, and press CTRL+C on your keyboard to copy that value.

![image](https://user-images.githubusercontent.com/19188146/84922183-810cc400-b093-11ea-9206-43615d31e851.png)

Now paste that value into Line 60 of config.ini, where it asks for a `cookie`. You can also configure various parts of the program, like where it should download the images, or if it should save metadata in JSON format, etc. Once you are finished, save the file and re-run `python PixivUtil2.py` in your command prompt. When it asks for a username and password, just press Enter twice. It will then try to login using the saved cookie you gave it earlier.

If all went well, you should now be able to use PixivUtil2! You can now use it however you need it do, be it downloading all of the artists that you follow, or downloading specific images or artists.
