### ISSUE TITLE
Downloading several pictures at once

### ISSUE THREAD

**Issue by ForxBase** [Nandaka/PixivUtil2#769]
Hello,

is it possible to download several pictures at once, like 5 pictures, to increase download speed? Right now it takes about 3-5 seconds to download 1 image. Can this be sped up? 

Best Regards

**Comment by rwchunk** [comment]
this is basically:
#685 
#504 
#477 
the details are there, but in short, no.
as someone who got a 'warning' once, I'd rather not attempt to push the boundaries again.

**Comment by ForxBase** [comment]
> this is basically:
> #685
> #504
> #477
> the details are there, but in short, no.
> as someone who got a 'warning' once, I'd rather not attempt to push the boundaries again.

What about just using a VPN? Also I've seen other downloaders from DeviantArt, you can download several images simultaneously.

**Comment by rwchunk** [comment]
> What about just using a VPN? Also I've seen other downloaders from DeviantArt, you can download several images simultaneously.

You probably _can_, not to say anything of whether or not your account gets banned. Its probably just done whenever the admin feels the need to do so, or is pressured by network costs, and just by random selection of people with high usages. Or perhaps certain ISPs/access points can't accurately be tracked. The worst case scenario would be that they decide to create strict limits on access or changing the site so that it can't easily be ripped. Granted, they've made their site worse for their bandwidth lately so maybe they won't care, or notice.

In any case, nandaka doesn't seem interested in doing it.
I'd say speed isn't really a necessity, I just can't imagine what situation you'd need to very quickly download artist works.
and you could always run multiple instances of the program.

**Comment by ForxBase** [comment]
> You probably _can_, not to say anything of whether or not your account gets banned. Its probably just done whenever the admin feels the need to do so, or is pressured by network costs, and just by random selection of people with high usages. Or perhaps certain ISPs/access points can't accurately be tracked. The worst case scenario would be that they decide to create strict limits on access or changing the site so that it can't easily be ripped. Granted, they've made their site worse for their bandwidth lately so maybe they won't care, or notice.
> 
> In any case, nandaka doesn't seem interested in doing it.
> I'd say speed isn't really a necessity, I just can't imagine what situation you'd need to very quickly download artist works.
> and you could always run multiple instances of the program.

Thanks for the feedback. You say you've been warned before. How much did you download before you got that warning? 

This is at the moment probably the best pixiv downloader there is, right? Together with the JD2.
