### ISSUE TITLE
Created a manga directory only uses the image ID for its name

### ISSUE THREAD

**Issue by MarqFJA87** [Nandaka/PixivUtil2#803]
### Prerequisites

* [x] Did you read FAQ section?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

When `createmangadir` is set to "True", any created manga directory only uses the image ID as its name.

### Steps to Reproduce

1. Set `createmangadir` to "True".
2. Confirm `filenamemangaformat` is set to `%artist% (%member_id%)\%urlFilename% - %title%`.
3. Download by member_id.

**Expected behavior:** The names of created directories follow the format `%urlFilename% - %title%`.

**Actual behavior:** The names of created directories follow the format `%urlFilename%`.

### Versions

Tested on v20200926-beta1

**Comment by Nandaka** [comment]
If you already `filenamemangaformat`, no need to set `createmangadir` to true.

**Comment by MarqFJA87** [comment]
`filenamemangaformat` was already set to what it was in the past while `createmangadir` was set to true, and it didn't led to any directories being created during downloading.

And I don't understand what you mean by referring to that part of the readme.md; am I missing something?

**Comment by Nandaka** [comment]
createmangadir  ==> Create a directory if the imageMode is manga. The directory
                   is created by splitting the **image_id** by '_pxx' pattern.
                   This setting is depended on **%urlFilename%** format.

**Comment by MarqFJA87** [comment]
Okay, I think I get it now. If I set `filenamemangaformat` `%artist% (%member_id%)\%image_id% - %title%\%urlFilename%`, would that make it work like I want it to?

**Comment by bluerthanever** [comment]
I think:
-If the image_id refers to a single image, then the `createmangadir` would do nothing.
-If the image_id refers to a manga, for example if one of the images' filename is `123456_big_p0.jpg`, and based on your filename format, the path would be like `artist (member_id)\123456 - title\123456_big_p0.jpg`, right? but since you set `createmangadir` to `True`, the whole path would be changed to `artist (member_id)\123456 - title\123456_big**\**_p0.jpg`. Notice the extra back slash in front of `_p0.jpg`, which means a folder would be created under `123456 - title` and all manga images would be saved inside it.

So if you have already set a folder path for manga, then you don't need to set `createmangadir` to `True`

**Comment by Nandaka** [comment]
@bluerthanever you are correct. Also, please note that `createmangadir` take priority (it is computed after the PixivHelper.make_filename() call)

Reference code: https://github.com/Nandaka/PixivUtil2/blob/master/PixivImageHandler.py#L235-L241

**Comment by MarqFJA87** [comment]
Tested it. Worked like a charm. The readme could do with a bit more clarification on this matter, though; I actually thought that `filenamemangaformat` works with `createmangadir`, not that they're independent from each other.
