### ISSUE TITLE
VPN usage

### ISSUE THREAD

**Issue by fontanellee** [Nandaka/PixivUtil2#984]
Cant use a requied template for this one. Pixiv got blocked in my country. What are the steps to make pixivutil work with vpn?

**Comment by NHOrus** [comment]
Get VPN, start it, check that Pixiv is getting through in browser, use PixivUtil, prepare to pay for a lot of traffic.

I'm using DigitalOcean droplet for 12$ a month, because I use droplet for other things, but minimum is 6$ and you still can use droplet for other things, installed WireGuard on it and on my home PC, and enjoying the stuff.

**Comment by Baa14453** [comment]
Once a VPN is active on your PC, standard practice routes all of your traffic through it so you don't need to do anything special for PixivUtil.
There are many VPN services available that have no data limit so you shouldn't need to pay too high.

**Comment by fontanellee** [comment]
It works. Thank you
